# Generated by Django 5.2.7 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='role',
            field=models.CharField(default='student'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
