# Generated by Django 5.2.7 on 2025-10-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_role_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
