# Generated by Django 5.2.7 on 2025-10-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_discription',
            new_name='course_description',
        ),
    ]
