# Generated by Django 5.2.7 on 2025-10-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_course_discription_courses_course_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
