# Generated by Django 5.2.7 on 2025-10-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_id_student_student_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
